apiVersion: apps/v1
kind: Deployment
metadata:
  name: testlog
  labels:
    app: testlog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testlog
  template:
    metadata:
      labels:
        app: testlog
    spec:
      containers:
      - name: testlog
        # image: 566780295057.dkr.ecr.ap-northeast-1.amazonaws.com/akawamura/test:latest
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello;sleep 10;done"]
        # args: ["-c", "while true; do /go/app/say-alphabet -bytes 1048576; echo ;echo hello;sleep 10;done"]
