image:
  repository: atkmr/fluentd-s3-es
  tag: es-test
  # repository: fluent/fluentd-kubernetes-daemonset
  # tag: v1.4-debian-s3
  pullPolicy: Always

resources:
  limits:
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 200Mi
