apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "fluentd.fullname" . }}
  labels:
{{ include "fluentd.labels" . | indent 4 }}
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fluentd.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "fluentd.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        kubernetes.io/cluster-service: "true"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccount: {{ include "fluentd.fullname" . }}
      serviceAccountName: {{ include "fluentd.fullname" . }}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      # hostNetwork: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-conf
        configMap:
          name: {{ include "fluentd.fullname" . }}
          items:
            - key: fluent.conf
              path: fluent.conf
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-env
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-conf
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        ports:
        - name: fluent-forward
          containerPort: 24224
          hostPort: 24224
          protocol: TCP
