apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  labels:
    app: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
      - name: console
        image: atkmr/awscli:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 100;done"]
